name: metadata_extract
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 1.0.0-nullsafety.0
homepage: https://github.com/safarmer/metadata_extract

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  string_validator: ^0.3.0
  html: ^0.15.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
